make:
	g++ -g index_and_quantify.cpp -lpthread -o index_and_quantify
run:
	./index_and_quantify ../data/Saccharomyces_cerevisiae.R64-1-1.cdna.all.fa ../data/queries.1M.fa 11 8
run_example:
	./index_and_quantify ../data/transcripts.fa ../data/queries.fa 3 2
clean:
	rm index_and_quantify
